const swaggerJsdoc = require('swagger-jsdoc');
const options = {
  // ADD THIS LINE!!!
  // List of files to be processed.
  apis: ["./config/swagger-docs.js"],
  // You can also set globs for your apis
  // e.g. './routes/*.js'
  basePath: "/",
  swaggerDefinition: {
    components: {},
    info: {
      description: "Test API with autogenerated swagger doc",
      swagger: "3.0",
      title: "Dessert API",
      version: "1.0.0"
    }
  }
};
const specs = swaggerJsdoc(options);
module.exports.default = specs;